language: java

jdk:
  - openjdk17

before_install:
  - chmod +x gradlew

install: true

script:
  - ./gradlew clean build
  - ./gradlew test
  - ./gradlew jacocoTestReport coveralls
  - ./gradlew sonarqube

addons:
  sonarcloud:
    organization: "tothanh93"
    token:
      secure: "fc4b11ee430b707eb11a48f8e04111f2e7069a9b"