language: java

jdk:
  - openjdk17

before_install:
  - chmod +x gradlew

env:
  global:
    - COVERALLS_REPO_TOKEN= SG1xOKBljDkBeh0mIcM1uIaf2cktEKTmf

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'

addons:
  sonarcloud:
    organization: "tothanh93"
    #token:
     # secure: "fc4b11ee430b707eb11a48f8e04111f2e7069a9b"
    projectKey: "tothanh93_desktop-test-app"


script:
  - ./gradlew test
  - ./gradlew build
  - sonar-scanner

after_success:
  - ./gradlew jacocoTestReport coveralls
