language: java

jdk:
  - openjdk17

  
before_install:
  - chmod +x gradlew

install: true

after_success:
  - ./gradlew jacocoTestReport coveralls


addons:
  sonarcloud:
    organization: "tothanh93"
    token:
      secure: "018b5241ea2d1fa2dda1de9599636f58f6d7d5b1"


script:
    - ./gradlew build
    - ./gradlew test
    - ./gradlew clean build
   