language: java

jdk:
  - openjdk11

  

install: true



addons:
  sonarcloud:
    organization: "tothanh93"
    token:
      secure: "fc4b11ee430b707eb11a48f8e04111f2e7069a9b"


script:
    - ./gradlew build
    - ./gradlew test
    - ./gradlew clean build
    - ./gradlew sonar