language: java

jdk:
  - openjdk21

install: true

script:
  - ./gradlew build
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport coveralls


addons:
  sonarcloud:
    organization: "tothanh93"
    token:
      secure: "4337567362a54106d21153f8895e7d5b92a739fb" 

script:
  - ./gradlew build
  - ./gradlew test
  - ./gradlew sonar
  - ./gradlew jacocoTestReport coveralls