language: java

jdk:
  - openjdk17

  
before_install:
  - chmod +x gradlew

install: true

after_success:
  - ./gradlew jacocoTestReport coveralls


addons:
  sonarcloud:
    organization: "tothanh93"
    token:
      secure: "4337567362a54106d21153f8895e7d5b92a739fb" 


script:
    - ./gradlew build
    - ./gradlew test
    - ./gradlew clean build
    - ./gradlew sonar
    - ./gradlew jacocoTestReport coveralls --debug
