language: java

jdk:
  - openjdk11

  
before_install:
  - chmod +x gradlew

install: true

after_success:
  - ./gradlew jacocoTestReport coveralls


addons:
  sonarcloud:
    organization: "tothanh93"
    token:
      secure: "70352cd34317b46ffcf4e5e9e7a4d2c3db277206"


script:
    - ./gradlew build
    - ./gradlew test
    - ./gradlew clean build
    - ./gradlew sonar