language: java

jdk:
  - openjdk17

  
before_install:
  - chmod +x gradlew

install: true

after_success:
  - ./gradlew jacocoTestReport coveralls


addons:
  sonarcloud:
    organization: "tothanh93"
    token:
      secure: "fc4b11ee430b707eb11a48f8e04111f2e7069a9b"


script:
    - ./gradlew build
    - ./gradlew test
    - ./gradlew clean build
    - ./gradlew sonar